# workflow name
name: blog-update-social

# master branch on push, auto run
on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update_social:
    runs-on: ubuntu-latest
    steps:
      - name: update_social_readme
        uses: zylele/social-readme@master
        with:
          douban_name: znyalor
          file_path: source/about/index.md
          gh_token: ${{ secrets.HEXO_DEPLOY_PRIVATE_KEY }}
