# workflow name
name: Social Readme CI

# auto run
on: 
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *'
      
jobs:
  update_social:
    runs-on: ubuntu-latest
    steps:
      - name: update_social_readme
        uses: zylele/social-readme@master
        with:
          blog_rss_link: https://zylele.github.io/atom.xml
          douban_name: znyalor
          file_path: source/about/index.md
